export default {
    name: 'siteSettings',
    title: 'Site Settings',
    type: 'document',
    groups: [
        { name: 'general', title: '🏠 기본 정보' },
        { name: 'contact', title: '📍 연락처 & 지도' },
        { name: 'homepage', title: '🖥️ 홈 화면 내용' },
    ],
    fields: [
        {
            name: 'title',
            title: 'Site Title (사이트 제목)',
            type: 'string',
            group: 'general',
            description: '헤더 로고 옆에 표시되는 연구실 이름 (예: AI & NLP Lab)',
            validation: (Rule: any) => Rule.required(),
        },
        {
            name: 'institution',
            title: 'Institution Name (소속 대학/기관)',
            type: 'string',
            group: 'general',
            description: '헤더 로고 아래에 작게 표시되는 대학 이름 (예: Korea University)',
        },
        {
            name: 'description',
            title: 'Site Description (사이트 설명)',
            type: 'text',
            group: 'general',
            description: 'SEO 및 Footer에 사용되는 연구실 소개 한 두 문장',
        },
        {
            name: 'logo',
            title: 'Logo (로고 이미지)',
            type: 'image',
            group: 'general',
            description: '헤더 왼쪽에 표시되는 로고 이미지. 정사각형 PNG 권장.',
            options: {
                hotspot: true,
            },
        },
        {
            name: 'email',
            title: 'Contact Email (이메일)',
            type: 'string',
            group: 'contact',
            description: 'Contact 페이지에 표시되는 대표 이메일 주소',
        },
        {
            name: 'phone',
            title: 'Phone Number (전화번호)',
            type: 'string',
            group: 'contact',
            description: 'Contact 페이지에 표시되는 전화번호 (예: +82-2-1234-5678)',
        },
        {
            name: 'address',
            title: 'Address (주소)',
            type: 'text',
            group: 'contact',
            rows: 3,
            description: 'Contact 페이지에 표시되는 연구실 주소 (여러 줄 가능)',
        },
        {
            name: 'officeHours',
            title: 'Office / Lab Hours (운영 시간)',
            type: 'array',
            group: 'contact',
            description: 'Contact 페이지 운영 시간 목록. 예: 월~금 / 09:00-18:00',
            of: [
                {
                    type: 'object',
                    fields: [
                        { name: 'days', type: 'string', title: '요일 (예: Mon-Fri)' },
                        { name: 'hours', type: 'string', title: '시간 (예: 9:00 AM – 6:00 PM)' },
                    ],
                },
            ],
        },
        {
            name: 'socialLinks',
            title: 'Social Media Links (SNS 링크)',
            type: 'object',
            group: 'contact',
            description: 'Footer 하단에 표시되는 SNS 링크들. 없으면 비워두세요.',
            fields: [
                { name: 'github', type: 'url', title: 'GitHub URL' },
                { name: 'twitter', type: 'url', title: 'Twitter/X URL' },
                { name: 'linkedin', type: 'url', title: 'LinkedIn URL' },
                { name: 'youtube', type: 'url', title: 'YouTube URL' },
            ],
        },
        {
            name: 'footerText',
            title: 'Custom Footer Text (Footer 문구)',
            type: 'string',
            group: 'general',
            description: 'Footer 하단 저작권 문구를 바꾸고 싶을 때 입력. 비워두면 자동 생성.',
        },
        {
            name: 'contactMessage',
            title: 'Contact Page Message (Contact 페이지 안내 문구)',
            type: 'text',
            group: 'contact',
            rows: 3,
            description: 'Contact 페이지 제목 아래에 표시되는 안내 문구',
        },
        {
            name: 'googleMapsUrl',
            title: 'Google Maps Embed URL (구글 지도 삽입 URL)',
            type: 'url',
            group: 'contact',
            description: 'Google Maps → "지도 공유" → "지도 삽입" → iframe의 src 값을 붙여넣기',
        },
        {
            name: 'directions',
            title: 'Directions (찾아오는 길)',
            type: 'text',
            group: 'contact',
            rows: 4,
            description: '지하철, 버스 등 교통편 안내 (Contact 페이지 하단 표시)',
        },
        {
            name: 'heroTitle',
            title: 'Hero Section Title (홈 메인 제목)',
            type: 'string',
            group: 'homepage',
            description: '홈 화면 상단 큰 제목 (기본값: "AI & NLP Research Laboratory")',
        },
        {
            name: 'heroSubtitle',
            title: 'Hero Section Subtitle (홈 메인 부제목)',
            type: 'text',
            rows: 2,
            group: 'homepage',
            description: '홈 화면 상단 큰 제목 아래에 표시되는 한두 문장',
        },
        {
            name: 'stats',
            title: 'Laboratory Statistics (연구실 통계 숫자)',
            type: 'array',
            group: 'homepage',
            description: '홈 화면 파란 배너에 표시되는 숫자 (예: 14+ / Publications)',
            of: [
                {
                    type: 'object',
                    fields: [
                        { name: 'value', type: 'string', title: '숫자 값 (예: 14+)' },
                        { name: 'label', type: 'string', title: '설명 (예: Publications)' },
                    ],
                },
            ],
        },
        {
            name: 'aboutExcerpt',
            title: 'Lab About Excerpt (홈 오른쪽 "About the Lab" 내용)',
            type: 'text',
            rows: 3,
            group: 'homepage',
            description: '홈 화면 오른쪽 사이드바 "About the Lab" 박스 안 텍스트',
        },
        {
            name: 'joinUsText',
            title: 'Join Us Text (하단 "Join Our Research Group" 문구)',
            type: 'text',
            rows: 2,
            group: 'homepage',
            description: '홈 화면 가장 아래 검정 배경 섹션의 부제목 문장',
        },
    ],
}
